import { Influencer } from '@/types'

export const MOCK_INFLUENCERS: Influencer[] = [
  {
    id: '1', slug: 'sara-ahm',
    full_name: 'سارة الأحمدي', handle: '@sara.ahm',
    bio: 'مؤثرة لايف ستايل وسفر من الرياض. أشارك تجاربي اليومية في الموضة والسفر والطعام مع متابعيني بشكل يومي وأصيل.',
    avatar_url: '',
    country: 'السعودية', city: 'الرياض', gender: 'female',
    niche: ['lifestyle', 'travel', 'fashion'],
    languages: ['العربية', 'الإنجليزية'],
    is_active: true, is_verified: true, is_featured: true, profile_views: 4820,
    created_at: '2024-01-10',
    total_followers: 1200000, avg_views: 420000, avg_engagement: 6.2,
    social_accounts: [
      { id: 's1', platform: 'instagram', handle: '@sara.ahm',   followers: 1200000, avg_views: 420000, engagement_rate: 6.2 },
      { id: 's2', platform: 'tiktok',    handle: '@saraahm',    followers: 845000,  avg_views: 680000, engagement_rate: 8.1 },
      { id: 's3', platform: 'snapchat',  handle: 'sara_ahm',    followers: 620000,  avg_views: 310000, engagement_rate: 4.9 },
    ],
    brand_names: ['H&M', 'Samsung', 'STC', 'Noon', 'Jarir'],
    collab_types: ['منشور ممول', 'ستوري إعلاني', 'ريلز', 'سفيرة علامة تجارية'],
  },
  {
    id: '2', slug: 'motech-sa',
    full_name: 'محمد التقني', handle: '@motech.sa',
    bio: 'مراجعات تقنية بلغة عربية بسيطة. أقدم أحدث المنتجات التقنية وأقارن بينها بشكل علمي وموضوعي.',
    avatar_url: '',
    country: 'السعودية', city: 'جدة', gender: 'male',
    niche: ['tech'],
    languages: ['العربية'],
    is_active: true, is_verified: true, is_featured: true, profile_views: 9200,
    created_at: '2023-08-22',
    total_followers: 3400000, avg_views: 1100000, avg_engagement: 4.8,
    social_accounts: [
      { id: 's4', platform: 'youtube',  handle: 'motech.sa',   followers: 3400000, avg_views: 1100000, engagement_rate: 4.8 },
      { id: 's5', platform: 'tiktok',   handle: '@motech',     followers: 2100000, avg_views: 890000,  engagement_rate: 6.3 },
      { id: 's6', platform: 'twitter',  handle: '@motech_sa',  followers: 890000,  avg_views: 0,       engagement_rate: 3.2 },
    ],
    brand_names: ['Apple', 'Samsung', 'Xiaomi', 'Lenovo', 'Noon'],
    collab_types: ['مراجعة منتج', 'فيديو ممول', 'منشور ممول'],
  },
  {
    id: '3', slug: 'noura-fashion',
    full_name: 'نورا الفيشن', handle: '@noura.fashion',
    bio: 'ستايليست ومؤثرة أزياء. أتخصص في الموضة المحتشمة العصرية والتشكيلات اليومية.',
    avatar_url: '',
    country: 'الإمارات', city: 'دبي', gender: 'female',
    niche: ['fashion', 'lifestyle'],
    languages: ['العربية', 'الإنجليزية'],
    is_active: true, is_verified: true, is_featured: false, profile_views: 3100,
    created_at: '2024-02-14',
    total_followers: 890000, avg_views: 310000, avg_engagement: 7.1,
    social_accounts: [
      { id: 's7', platform: 'instagram', handle: '@noura.fashion', followers: 890000, avg_views: 310000, engagement_rate: 7.1 },
      { id: 's8', platform: 'snapchat',  handle: 'noura_f',        followers: 650000, avg_views: 280000, engagement_rate: 5.4 },
      { id: 's9', platform: 'tiktok',    handle: '@noura_fsh',     followers: 420000, avg_views: 510000, engagement_rate: 9.2 },
    ],
    brand_names: ['Zara', 'Mango', 'ALDO', 'Dune', 'Level Shoes'],
    collab_types: ['منشور ممول', 'ستوري', 'تغطية فعالية'],
  },
  {
    id: '4', slug: 'ahmed-eats',
    full_name: 'أحمد الطعام', handle: '@ahmed.eats',
    bio: 'صانع محتوى طعام ومطاعم. أزور أفضل المطاعم وأشارك تجاربي الصادقة والصريحة.',
    avatar_url: '',
    country: 'السعودية', city: 'الدمام', gender: 'male',
    niche: ['food', 'lifestyle'],
    languages: ['العربية'],
    is_active: true, is_verified: false, is_featured: false, profile_views: 2700,
    created_at: '2024-03-01',
    total_followers: 2100000, avg_views: 780000, avg_engagement: 5.9,
    social_accounts: [
      { id: 's10', platform: 'instagram', handle: '@ahmed.eats',  followers: 2100000, avg_views: 780000,  engagement_rate: 5.9 },
      { id: 's11', platform: 'snapchat',  handle: 'ahmed_eats',   followers: 1400000, avg_views: 620000,  engagement_rate: 4.7 },
      { id: 's12', platform: 'tiktok',    handle: '@ahmed_eats',  followers: 980000,  avg_views: 1100000, engagement_rate: 7.8 },
    ],
    brand_names: ['البيك', 'Almarai', 'Nandos', 'Herfy'],
    collab_types: ['زيارة مطعم', 'مراجعة منتج', 'منشور ممول'],
  },
  {
    id: '5', slug: 'layla-motors',
    full_name: 'ليلى السيارات', handle: '@layla.motors',
    bio: 'أول مؤثرة سعودية متخصصة في عالم السيارات. مراجعات صريحة ومقارنات تفصيلية.',
    avatar_url: '',
    country: 'السعودية', city: 'الرياض', gender: 'female',
    niche: ['auto'],
    languages: ['العربية', 'الإنجليزية'],
    is_active: true, is_verified: true, is_featured: true, profile_views: 6400,
    created_at: '2023-11-05',
    total_followers: 1800000, avg_views: 920000, avg_engagement: 5.4,
    social_accounts: [
      { id: 's13', platform: 'youtube',  handle: 'layla.motors',   followers: 1800000, avg_views: 920000,  engagement_rate: 5.4 },
      { id: 's14', platform: 'tiktok',   handle: '@layla_motors',  followers: 1200000, avg_views: 1400000, engagement_rate: 7.2 },
      { id: 's15', platform: 'twitter',  handle: '@layla_motors',  followers: 340000,  avg_views: 0,       engagement_rate: 2.9 },
    ],
    brand_names: ['Toyota', 'Lexus', 'BMW', 'Mercedes'],
    collab_types: ['مراجعة سيارة', 'تغطية معرض', 'فيديو ممول'],
  },
  {
    id: '6', slug: 'khalid-biz',
    full_name: 'خالد الأعمال', handle: '@khalid.biz',
    bio: 'رائد أعمال ومستشار استراتيجي. أشارك خلاصة تجربتي في ريادة الأعمال والاستثمار.',
    avatar_url: '',
    country: 'السعودية', city: 'الرياض', gender: 'male',
    niche: ['business'],
    languages: ['العربية', 'الإنجليزية'],
    is_active: true, is_verified: true, is_featured: true, profile_views: 12000,
    created_at: '2023-06-18',
    total_followers: 4200000, avg_views: 1500000, avg_engagement: 3.9,
    social_accounts: [
      { id: 's16', platform: 'youtube',   handle: 'khalid.biz',   followers: 4200000, avg_views: 1500000, engagement_rate: 3.9 },
      { id: 's17', platform: 'twitter',   handle: '@khalid_biz',  followers: 3100000, avg_views: 0,       engagement_rate: 2.8 },
      { id: 's18', platform: 'instagram', handle: '@khalid.biz',  followers: 1800000, avg_views: 420000,  engagement_rate: 4.2 },
    ],
    brand_names: ['STC Pay', 'Riyad Bank', 'Misk'],
    collab_types: ['منشور ممول', 'بودكاست', 'محاضرة', 'سفير علامة'],
  },
  {
    id: '7', slug: 'reem-sport',
    full_name: 'ريم الرياضة', handle: '@reem.sport',
    bio: 'مدربة لياقة بدنية معتمدة ومؤثرة رياضية. أساعدك تعيش أسلوب حياة صحي ومتوازن.',
    avatar_url: '',
    country: 'السعودية', city: 'جدة', gender: 'female',
    niche: ['sports', 'lifestyle'],
    languages: ['العربية'],
    is_active: true, is_verified: false, is_featured: false, profile_views: 1900,
    created_at: '2024-04-20',
    total_followers: 650000, avg_views: 240000, avg_engagement: 8.3,
    social_accounts: [
      { id: 's19', platform: 'instagram', handle: '@reem.sport',  followers: 650000, avg_views: 240000,  engagement_rate: 8.3  },
      { id: 's20', platform: 'tiktok',    handle: '@reem_sport',  followers: 890000, avg_views: 1200000, engagement_rate: 11.2 },
    ],
    brand_names: ['Nike', 'Adidas', 'GNC', 'MyProtein'],
    collab_types: ['منشور ممول', 'ستوري', 'تحدي رياضي'],
  },
  {
    id: '8', slug: 'faisal-travel',
    full_name: 'فيصل المسافر', handle: '@faisal.travel',
    bio: 'صانع محتوى سفر وتصوير. أوثّق رحلاتي حول العالم ببراعة بصرية وقصص ملهمة.',
    avatar_url: '',
    country: 'السعودية', city: 'الرياض', gender: 'male',
    niche: ['travel', 'lifestyle'],
    languages: ['العربية', 'الإنجليزية'],
    is_active: true, is_verified: true, is_featured: false, profile_views: 5300,
    created_at: '2023-09-12',
    total_followers: 2800000, avg_views: 890000, avg_engagement: 4.6,
    social_accounts: [
      { id: 's21', platform: 'instagram', handle: '@faisal.travel', followers: 2800000, avg_views: 890000,  engagement_rate: 4.6 },
      { id: 's22', platform: 'youtube',   handle: 'faisal.travel',  followers: 1200000, avg_views: 1800000, engagement_rate: 5.8 },
      { id: 's23', platform: 'tiktok',    handle: '@faisal_travel', followers: 980000,  avg_views: 1400000, engagement_rate: 7.1 },
    ],
    brand_names: ['Almosafer', 'Hilton', 'Flyadeal', 'Saudia'],
    collab_types: ['تغطية وجهة', 'محتوى فندق', 'منشور ممول', 'مراجعة طيران'],
  },
]
